name: Deploy Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  deploy_dev:
    name: "Deploy to Dev"
    runs-on: ubuntu-latest

    steps:
      - name: Deploy pipeline
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /home/server/minetest
            
            echo ""
            echo "[STAGE 1/4] Sync git & Apply Overrides"
            echo "-----------------------------------------"
            
            echo "[INFO] Синхронизация с origin/dev..."
            git checkout dev
            git fetch origin dev
            git reset --hard origin/dev
            
            chmod +x apply-overrides.sh checker.sh
            
            echo "[INFO] Применение overrides..."
            ./apply-overrides.sh
            
            echo "[INFO] Фиксация Состояния B..."
            git add .
            git commit -m "ci: temporary state B for checker"
            
            echo "[OK] Stage 1 завершена"
            
            echo ""
            echo "[STAGE 2/4] Restart Server"
            echo "-----------------------------------------"
            
            # TODO: ВСТАВИТЬ КОМАНДУ/СКРИПТ РЕСТАРТА СЕРВЕРА С ПРОВЕРКОЙ УСПЕШНОГО ЗАПУСКА
            # ./start.sh
            # screen -dmS mc_dev ./start.sh
            # sleep 15
            
            echo "[OK] Stage 2 завершена"
            
            echo ""
            echo "[STAGE 3/4] Check Changes"
            echo "-----------------------------------------"
            
            echo "[INFO] Запуск Checker'а..."
            ./checker.sh
            
            echo "[OK] Stage 3 завершена"
            
            echo ""
            echo "[STAGE 4/4] Cleanup"
            echo "-----------------------------------------"
            
            echo "[INFO] Очистка временного коммита..."
            git reset --soft HEAD~1
            git reset HEAD
            
            echo ""
            echo "========================================="
            echo "[OK] DEPLOY COMPLETED SUCCESSFULLY"
            echo "========================================="